### PR TITLE
Nikon PictureControl directory extraction

### PR DESCRIPTION
**Pull request by gtiwari333**
This PR ports the change that were made on C# repo to this Java repo. https://github.com/drewnoakes/metadata-extractor-dotnet/pull/341/files

### CODE REVIEW

**Comment by gtiwari333** [comment]
https://github.com/drewnoakes/metadata-extractor/pull/634  

Opened this new PR.

**Comment by gtiwari333** [comment]
@drewnoakes I would really appreciate if you review/merge/release this PR.

**Review by drewnoakes — APPROVED** [review]

**Comment by drewnoakes** [comment]
I ran the regression tests, pushed a few updates to this PR, merged it, and tried to make a release. I hit an error and had to upgrade a maven plugin. Now I'm hitting another error:

```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:release (default-cli) on project metadata-extractor: Execution default-cli of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:release failed: No converter available
[ERROR] ---- Debugging information ----
[ERROR] message             : No converter available
[ERROR] type                : java.util.Arrays$ArrayList
[ERROR] converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @316acbb5
[ERROR] -------------------------------
```

Any ideas about this? I'm out of time to look at this today.

**Comment by drewnoakes** [comment]
In the end I found a workaround here, via:

```
export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
```

Your change should be available in 2.19.0. Let me know if you hit any issues.

**Comment by Nadahar** [comment]
> In the end I found a workaround [here](https://issues.sonatype.org/browse/OSSRH-66257?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=1126446#comment-1126446), via:
> 
> ```
> export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
> ```
Bitten by some of the new restrictions in more recent Java versions it seems. Use Java 8 and those things don't exist 😉

**Comment by drewnoakes** [comment]
Sounds like going back to Java 8 would be a good step forward 😆

**Pull request merged**
