### PR TITLE
Extended XMP support

### PR DESCRIPTION
**Pull request by rcketscientist**
Support for reading and writing some xmp tags.

### CODE REVIEW

**Comment by rcketscientist** [comment]
I'm new to the whole git process.  I couldn't figure out how to ignore the Android-related files or the project files.  If I jacked anything up please let me know so I can fix it and for future reference.  Thanks.

**Comment by drewnoakes** [comment]
Thanks for these. There are quite a few changes here and it'll take me a while to review them all. Unfortunately it looks like your IDE replaces space with tabs, so the diff is a bit hard to read. Also it seems that the build is broken.

Can you comment on the gradle build and the android manifest? I don't know about either of these. Are they of general interest for the library? Ideally they'd each be a separate pull request.

I hope to look at this either on Friday or over the weekend. Thanks again for taking the time to put this PR together.

**Comment by drewnoakes** [comment]
(Relates to #38)

**Comment by rcketscientist** [comment]
gradle is the build system for Android apps.  Android manifest is the manifest that defines the app api/rights, etc.  Neither of these are necessary at all for the main library.  I'm just not sure how to exclude them.

Sorry for the screwy PR.  I'm new to collaborating in git.  **If you know how I can correct this PR to segregate the android files and the actual code, please let me know and I'll fix it.** I have absolutely no problem taking the time to get this right, so don't waste your own time if I can fix it.

What do you use for dif?  Perhaps you can ignore whitespace.  I'll also apply a separate code style to metadata-extractor in the future to avoid the whitespace issue.  **Is it just a space vs. tab thing?  Do you have idea settings (I noticed the iml)?**  I could probably apply them and check it back in.  

Speaking of, I should also ignore the iml somehow.  **Is this just a matter of making separate commits for these project organization files and excluding those specific commits somehow?**

As for the build I confirmed the build works here for read/write/modify of xmp rating/label/subject.  **Let me know how the build is failing over there and I'll take a look.**

**Comment by rcketscientist** [comment]
Spent the morning researching collaborating with differing ide and somehow can't find a damn thing.  The only thing I can come up with is maintaining a branch with .gitignore entries for those files from which I'd make pull requests.  Does this make sense?

Let me know about the whitespace issue, I'll adjust all the files to conform.

**Comment by rcketscientist** [comment]
Just got a super-fast reply on StackOverflow and I think there's a sensible solution isolating the android changes into their own branch.  I think I will have to start from scratch on this again however, so I'll work on the various issues and submit again later.

**Pull request closed without merging**
