### PR TITLE
Extended XMP support

### PR DESCRIPTION
**Pull request by rcketscientist**
Includes:

 read, write, and modify of
 'rating', 'label', 'subject' tags

### CODE REVIEW

**Comment by rcketscientist** [comment]
OK, I think I fixed that mess.  Not sure if there's a way to avoid the gitignore and iml changes, but whitespace should be cleaned up.

**Comment by drewnoakes** [comment]
Hey thanks -- I'd hoped to look at this last Sunday but didn't have time. Just wanted to let you know I haven't forgotten this PR and that it looks great. Will do some testing with it this weekend and get back to you.

**Comment by rcketscientist** [comment]
Sounds good, the code is rather old and I basically just shoehorned in the new API, so let me know if you need help understanding anything and/or some modifications to fit the new scheme.

**Comment by drewnoakes** [comment]
Looks great. Thanks!

**Pull request merged**
