### PR TITLE
Refactor date processing

### PR DESCRIPTION
**Pull request by drewnoakes**
Moves epoch conversion code to `DateUtil` and other minor tweaks.

//cc: @Nadahar @payton @kwhopper

### CODE REVIEW

**Comment by drewnoakes** [comment]
I've disabled codefactor.

Still not sure why we have two Travis builds, where one never completes.

**Comment by drewnoakes** [comment]
> Still not sure why we have two Travis builds, where one never completes

Never mind. It completed.

**Comment by Nadahar** [comment]
> Still not sure why we have two Travis builds, where one never completes.

It's a GitHub/Travis issue - it's like that for everybody. One is for the commit and one is for the PR. If you push a new commit that's not part of a PR, it will build just the "push" one. If somebody creates a PR from an external repository (see e.g. #395), only the "pr" one will be built.

For some reason unknown to me, they haven't managed to eliminate these "double builds" when they are actually triggered on the same commit. AFAICR the "push" is started before the "pr" one, so the "pr" one will lag behind in completion.

As I mentioned in #410, you could have just guided me and I would have moved the code to where you wanted it (and renamed variables etc.), but doing it this way is fine too. I guess you figured it was easier to just do than to explain :wink:

**Comment by drewnoakes** [comment]
Thanks for the explanation regarding the travis builds. I misremembered, but actually the problem is with the AppVeyor build of .NET PRs (for example https://github.com/drewnoakes/metadata-extractor-dotnet/pull/188) where one stays in 'expected' for ages, never completes and blocks a non-admin merge.

> I guess you figured it was easier to just do than to explain

No that wasn't my thinking. After merging I was playing around with it out of curiosity really and this is where I landed.

**Pull request merged**
