### PR TITLE
Upgrade com.adobe.xmp to latest 6.1.10

### PR DESCRIPTION
**Pull request by elevenfive**

### CODE REVIEW

**Comment by drewnoakes** [comment]
Thanks for the patch.

The build is failing. Can you fix it?

**Comment by elevenfive** [comment]
So, there is a problem with one of the tests, XmpReaderTest, it is expecting 179 objects but is finding 178, I'm not sure why.  I have also tried to convert the project to gradle but I'm not sure how to migrate the publishing side of the equation.  Feel free to see the branch:  https://github.com/elevenfive/metadata-extractor/tree/gradle

**Comment by drewnoakes** [comment]
I'm not clear why Adobe doesn't link to a 6.x version from their XMPCore page. They recently changed from 5.1.2 to 5.1.3. Do you know anything about the 6.x family?

**Comment by elevenfive** [comment]
I think they upgraded it this summer, but have not updated their website for the 6.0 java version.  I'll close this until they make docs public, thanks!

**Pull request closed without merging**
