### PR TITLE
Fix some null pointer exceptions in MP4 code

### LINKED ISSUE #368: NullpointerException when parsing GoPro MP4 videos
When trying to extract metadata from GoPro MP4 videos, metatadata-extractor throws a NullpointerException:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.drew.metadata.mp4.Mp4MediaHandler.<init>(Mp4MediaHandler.java:50)
	at com.drew.metadata.mp4.media.Mp4MetaHandler.<init>(Mp4MetaHandler.java:36)
	at com.drew.metadata.mp4.Mp4HandlerFactory.getHandler(Mp4HandlerFactory.java:61)
	at com.drew.metadata.mp4.Mp4BoxHandler.processBox(Mp4BoxHandler.java:82)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:58)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.extract(Mp4Reader.java:42)
	at com.drew.imaging.mp4.Mp4MetadataReader.readMetadata(Mp4MetadataReader.java:57)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:178)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:125)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:205)

Please try this sample video:
https://testing.jalbum.net/bugreport/GOPR0158.MP4

### PR DESCRIPTION
**Pull request by drewnoakes**
Closes #368.

@payton if you're happy with these changes, please go ahead and merge the PR, or feel free to push your own changes to it. Thanks!

### CODE REVIEW

**Comment by drewnoakes** [comment]
@davidekholm please also take a look at these changes.

**Comment by davidekholm** [comment]
Thanks. The code seems to behave now.

**Comment by himslm01** [comment]
Any ideas when this fix is going to be released?
I'm going through the hundreds of thousands of media files I have, and it's annoying that the GoPro MP4 files are causing the throwing of this runtime exception.

**Comment by mtbkeith** [comment]
I had the same issue. You can build the snapshot version locally and
reference that in your local build.

**Comment by Nadahar** [comment]
@drewnoakes @payton Isn't it time for a release now anyway, or is something holding it up?

**Comment by drewnoakes** [comment]
I think we're in good shape for a release. I'm catching up with a tonne of stuff that piled up during the holidays, but have put this on my list.

**Comment by Parvizm1991** [comment]
@drewnoakes  still not a time for a release? that would be nice to have it soon :) . Thanks

**Pull request merged**
