### PR TITLE
Minormods

### PR DESCRIPTION
**Pull request by palantir0**
Fixed a couple of build issues with dates.
Added Lens Type for Canon.

### CODE REVIEW

**Comment by drewnoakes** [comment]
Looks good. I'll check it in more detail in the next day or two.

**Comment by drewnoakes** [comment]
Out of curiosity, what time zone were you running these tests in that caused them to fail?

**Comment by drewnoakes** [comment]
On the whole this is great. If you wouldn't mind extending the new fstop formatting to the FNumber tag as discussed (I think that's the only other instance), I'll merge this in.

**Comment by palantir0** [comment]
Oh, it was PST timezone.  If I get some more time I'll add the special lens tags that goes with the canon lens tag edit.  I'm doing that outside of the library currently so it needs to be added differently than I'm doing it now.

**Comment by drewnoakes** [comment]
Thanks very much for the PR.

I'm interested to hear if any of what you're doing outside the library would be a good fit for inside the library.

**Pull request merged**
