### PR TITLE
Added cobertura to the build

### PR DESCRIPTION
**Pull request by sksamuel**
Added cobertura to the build
Updated travis to invoke coverage

### CODE REVIEW

**Comment by drewnoakes** [comment]
Have patched this in #114 and am waiting for the build to run.

How would these results be surfaced?

**Comment by sksamuel** [comment]
Next task is: https://github.com/trautonen/coveralls-maven-plugin

**Comment by sksamuel** [comment]
@drewnoakes green now

**Comment by drewnoakes** [comment]
Great. Do I need to set up anything with coveralls.io or will it integrate directly?

**Comment by sksamuel** [comment]
Yep, should just be a case of adding that coveralls plugin now.

**Comment by drewnoakes** [comment]
Is that added in the <profile> section you created, or alongside the
previously existing plugins?

**Comment by sksamuel** [comment]
Put it inside the profile I made. That way it'll only fire when you do
-Pcoverage.

**Comment by sksamuel** [comment]
If you merge this, so coverage is generated, I'll do another PR with the plugin to send the data to coveralls (you'll need to create a project there, it's just like travis, login with your github creds).

**Comment by drewnoakes** [comment]
Will do in the next little while. Would be good to sort this out.

**Comment by drewnoakes** [comment]
Thanks, it's pushed.

Have created a coveralls.io account and project (actually this already existed):

https://coveralls.io/r/drewnoakes/metadata-extractor

Added the plugin to the pom.xml too. Now just waiting for a build.

**Comment by sksamuel** [comment]
Should just work :)

**Comment by drewnoakes** [comment]
Made a few more changes and travis is now kicking off `mvn clean cobertura:cobertura coveralls:report` on `after_success`.

Unfortunately that step downloads plugins [then fails](https://travis-ci.org/drewnoakes/metadata-extractor/jobs/68968560#L2446):

>  No plugin found for prefix 'coveralls' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/travis/.m2/repository)

My Maven-fu isn't strong. Do you know what's going on here?

**Comment by sksamuel** [comment]
Is this on master?

**Comment by drewnoakes** [comment]
Yes.

**Comment by sksamuel** [comment]
need to change this:
mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin
:report
to
mvn -Pcoverage clean cobertura:cobertura org.eluder.coveralls:
coveralls-maven-plugin:report
to activiate the plugins as they're inside a profile. They're in a profile
because I'm not sure if they run by default (and you probably don't want
them to).

**Comment by drewnoakes** [comment]
Awesome. Cheers!

Now to increase the coverage...

**Pull request closed without merging**
