### PR TITLE
Ading StringValue changes from dotnet version to java version, plus fix for PanasonicMakernotes

### PR DESCRIPTION
**Pull request by daniel6651**
Hi

Tried to implement the same changes as in 
https://github.com/drewnoakes/metadata-extractor-dotnet/pull/34
for Java.

Noticed that it did not help in my particular case, where PanasonicMakernotes did not get UTF-8 characters correctly. I think I managed to find a solution for that as well. Added a small test for that.

BR

Daniel Persson

### CODE REVIEW

**Comment by drewnoakes** [comment]
Great! I'll take a look asap. Unfortunately there's a bunch of reformatting in there (see [this](https://github.com/drewnoakes/metadata-extractor/blob/master/CONTRIBUTING.md)), so I won't just merge the PR as it's hard to see what's going on and will make the formatting inconsistent throughout the project. If you back that out I'll review it and merge the PR, otherwise I'll have to edit it manually, probably on the weekend.

Thanks for taking the time to follow up with this.

As for your issues with Panasonic makernote text, can you attach a sample image that I can use to take a look at?

The CI build failed. It looks like you forgot to include a test image for `JpegMetadataReaderTest.testExtractPanasonicMakernoteMetadata`:

https://travis-ci.org/drewnoakes/metadata-extractor/jobs/153242353#L1934

**Comment by daniel6651** [comment]
Hi Drew
The build problems was due to incorrect case in the filename in the test case ".jpg" instead of ".JPG". Works on Windows so tat's why I didn't notice it. I pushed a new commit for it now. Hope that is all it takes for you to see it - I'm new to GitHub...
I added a file in the test/Data directory which I use in the new test case. It contains Panasonic makernote with danish character in the state tag.
What is the formatting to be used to get it right? I use netbeans and must have done intendation of the entire changed file by mistake somewhere then.
BR
Daniel 

    Den torsdag, 18 augusti 2016 15:19 skrev Drew Noakes <notifications@github.com>:
 

 Great! I'll take a look asap. Unfortunately there's a bunch of reformatting in there (see this), so I won't just merge the PR as it's hard to see what's going on and will make the formatting inconsistent throughout the project. If you back that out I'll review it and merge the PR, otherwise I'll have to edit it manually, probably on the weekend.Thanks for taking the time to follow up with this.As for your issues with Panasonic makernote text, can you attach a sample image that I can use to take a look at?The CI build failed. It looks like you forgot to include a test image for JpegMetadataReaderTest.testExtractPanasonicMakernoteMetadata:https://travis-ci.org/drewnoakes/metadata-extractor/jobs/153242353#L1934—

**Comment by drewnoakes** [comment]
No worries. If you're on Windows then you might like to try using Git Extensions to commit code. It lets you see all the lines that changed, and you can stage/unstage/reset individual lines of code before committing. Prevents surprises.

I'll use the test file as the basis for further testing.

If you'd like to run a regression test with your changes you can do so using the [image library](https://github.com/drewnoakes/metadata-extractor-images/wiki).

**Comment by drewnoakes** [comment]
Looking at this again now.

I'd hoped you might revert the formatting changes as discussed, but I'll take a shot at it now. Unfortunately I can't merge this as is, so will have to re-do your changes manually.

Another challenge with this PR is that it introduces Java features that require Java 1.7 (such as `java.nio.charset`). Currently the lib only requires Java 1.5.

Also we avoid adding test images to the repository. More information [here](https://github.com/drewnoakes/metadata-extractor/wiki/Working-with-test-images).

**Comment by drewnoakes** [comment]
It took a while but I got through the manual update. In the end it was easiest just to port over the changes myself. There we other changes in the .NET version that weren't reflected in your PR as well (in later commits than the ones you looked at, as far as I can tell).

Thanks for the nudge on this. It's a good improvement to the library. Your Panasonic sample image was added to the sample images repo too, and you can see the correct interpretation of the non-Latin characters there.

**Pull request closed without merging**
