### PR TITLE
Overflowing a short length so it goes negative and screws up the byte…

### PR DESCRIPTION
**Pull request by sergeyplokhikh**
… read pointer

### CODE REVIEW

**Comment by drewnoakes** [comment]
@sergeyplokhikh thanks for this. Do you have an image that exhibits this problem that you can share with the project?

**Comment by sergeyplokhikh** [comment]
> @sergeyplokhikh thanks for this. Do you have an image that exhibits this problem that you can share with the project?

Images I have are a customers so we can’t share directly but I'll see if I can sanitize one.

**Comment by sergeyplokhikh** [comment]
[PhotoshopReaderSample.psd.zip](https://github.com/drewnoakes/metadata-extractor/files/5810673/PhotoshopReaderSample.psd.zip)

**Comment by drewnoakes** [comment]
@sergeyplokhikh thanks very much for following up with the file. Appreciate it.

**Pull request merged**
